This is for Unit 3 for CS379.  we take a creditcard file and run it through a prection file to detect fraud.

In [69]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report


CCFraud = pd.read_csv("csv_result-creditfruad original.csv") #loads dataset into program.

CCFraud.info() #displays information about dataset.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   id                      1000 non-null   int64 
 1   over_draft              1000 non-null   object
 2   credit_usage            1000 non-null   int64 
 3   credit_history          1000 non-null   object
 4   purpose                 1000 non-null   object
 5   current_balance         1000 non-null   int64 
 6   Average_Credit_Balance  1000 non-null   object
 7   employment              1000 non-null   object
 8   location                1000 non-null   int64 
 9   personal_status         1000 non-null   object
 10  other_parties           1000 non-null   object
 11  residence_since         1000 non-null   int64 
 12  property_magnitude      1000 non-null   object
 13  cc_age                  1000 non-null   int64 
 14  other_payment_plans     1000 non-null   object
 15  housi

In [70]:
CCFraud.head(10) #shows first 10 lines of dataset so you vcan see values by column.

id   over_draft  credit_usage                  credit_history  \
0   1           <0             6  critical/other existing credit   
1   2     0<=X<200            48                   existing paid   
2   3  no checking            12  critical/other existing credit   
3   4           <0            42                   existing paid   
4   5           <0            24              delayed previously   
5   6  no checking            36                   existing paid   
6   7  no checking            24                   existing paid   
7   8     0<=X<200            36                   existing paid   
8   9  no checking            12                   existing paid   
9  10     0<=X<200            30  critical/other existing credit   

               purpose  current_balance Average_Credit_Balance  employment  \
0             radio/tv             1169       no known savings         >=7   
1             radio/tv             5951                   <100      1<=X<4   
2            education             2096                   <100      4<=X<7   
3  furniture/equipment             7882                   <100      4<=X<7   
4              new car             4870                   <100      1<=X<4   
5            education             9055       no known savings      1<=X<4   
6  furniture/equipment             2835            500<=X<1000         >=7   
7             used car             6948                   <100      1<=X<4   
8             radio/tv             3059                 >=1000      4<=X<7   
9              new car             5234                   <100  unemployed   

   location     personal_status  ... property_magnitude  cc_age  \
0         4         male single  ...        real estate      67   
1         2  female div/dep/mar  ...        real estate      22   
2         2         male single  ...        real estate      49   
3         2         male single  ...     life insurance      45   
4         3         male single  ...  no known property      53   
5         2         male single  ...  no known property      35   
6         3         male single  ...     life insurance      53   
7         2         male single  ...                car      35   
8         2        male div/sep  ...        real estate      61   
9         4        male mar/wid  ...                car      28   

  other_payment_plans   housing existing_credits                        job  \
0                none       own                2                    skilled   
1                none       own                1                    skilled   
2                none       own                1         unskilled resident   
3                none  for free                1                    skilled   
4                none  for free                2                    skilled   
5                none  for free                1         unskilled resident   
6                none       own                1                    skilled   
7                none      rent                1  high qualif/self emp/mgmt   
8                none       own                1         unskilled resident   
9                none       own                2  high qualif/self emp/mgmt   

   num_dependents own_telephone  foreign_worker class  
0               1           yes             yes  good  
1               1          none             yes   bad  
2               2          none             yes  good  
3               2          none             yes  good  
4               2          none             yes   bad  
5               2           yes             yes  good  
6               1          none             yes  good  
7               1           yes             yes  good  
8               1          none             yes  good  
9               1          none             yes   bad  

[10 rows x 22 columns]

In [71]:
print(CCFraud.columns)  #gives us the column names for hte dataset.

print(CCFraud['class'].unique()) #gives us a list of fraud inputs

print(CCFraud['class'].value_counts()) #tells us how many charges were considered fraud within the dataset

Index(['id', 'over_draft', 'credit_usage', 'credit_history', 'purpose',
       'current_balance', 'Average_Credit_Balance', 'employment', 'location',
       'personal_status', 'other_parties', 'residence_since',
       'property_magnitude', 'cc_age', 'other_payment_plans', 'housing',
       'existing_credits', 'job', 'num_dependents', 'own_telephone',
       'foreign_worker', 'class'],
      dtype='object')
['good' 'bad']
good    700
bad     300
Name: class, dtype: int64


In [72]:
CCFraud = CCFraud.drop(['over_draft', 'credit_history', 'purpose', 'Average_Credit_Balance', 'employment', 'location', 'personal_status', 'other_parties', 'property_magnitude', 'other_payment_plans', 'housing', 'job', 'num_dependents', 'own_telephone', 'foreign_worker'], axis = 1) #drops unneeded values from dataset

print(CCFraud.columns) #prints remaining values

Index(['id', 'credit_usage', 'current_balance', 'residence_since', 'cc_age',
       'existing_credits', 'class'],
      dtype='object')


Prepairing to split and train the data starts here.

In [73]:
labels = LabelEncoder()

CCFraud.iloc[:,6] = labels.fit_transform(CCFraud.iloc[:,6].values) #transform class into values

print(CCFraud['class'].unique()) #prints class values

[1 0]


In [74]:
X = CCFraud.iloc[: , 1:8] #splits data into 80%training
Y = CCFraud.iloc[: , 0] #and 20 percent testing

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .6, random_state = 0) #actual split of data into testing and training

SD = StandardScaler() #scaled dataset
X_train = SD.fit_transform(X_train)
X_test = SD.transform(X_test)


Decision tree algorithm has given me the best success with this dataset in terms of accuricy.

In [75]:
DETFraud = DecisionTreeClassifier() #decision tree for classification fits dataset best.

DETFraud.fit(X_train, Y_train)

y_pred_decision_tree = DETFraud.predict(X_test)

acc_decision_tree = DETFraud.score(X_train, Y_train) 

print (acc_decision_tree) #decision tree logic.

print (confusion_matrix(Y_test, y_pred_decision_tree)) #shows confusion matrix from trained data to look at



1.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
